/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    AccordionPanel: typeof import('primevue/accordionpanel')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CharacterListMenu: typeof import('./src/components/character-list/CharacterListMenu.vue')['default']
    CharacterSettings: typeof import('./src/components/character-settings/CharacterSettings.vue')['default']
    DialogAddCharacter: typeof import('./src/components/character-list/DialogAddCharacter.vue')['default']
    DialogAddFolder: typeof import('./src/components/character-list/DialogAddFolder.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MacrosPanel: typeof import('./src/components/magic-list/MacrosPanel.vue')['default']
    MainTabs: typeof import('./src/components/main-page/MainTabs.vue')['default']
    Select: typeof import('primevue/select')['default']
    SpellCard: typeof import('./src/components/spell-card/SpellCard.vue')['default']
    SpellCardWrapper: typeof import('./src/components/spell-card-wrapper/SpellCardWrapper.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
}
