/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    CharacterListMenu: typeof import('./src/components/character-list/CharacterListMenu.vue')['default']
    CharacterSettings: typeof import('./src/components/character-settings/CharacterSettings.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DialogAddCharacter: typeof import('./src/components/character-list/DialogAddCharacter.vue')['default']
    DialogAddFolder: typeof import('./src/components/character-list/DialogAddFolder.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MacrosPanel: typeof import('./src/components/magic-list/MacrosPanel.vue')['default']
    MainTabs: typeof import('./src/components/main-page/MainTabs.vue')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    Select: typeof import('primevue/select')['default']
    SpeedDial: typeof import('primevue/speeddial')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
